apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms-provider-mock
    environment: Development
  name: sms-provider-mock
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sms-provider-mock
  sessionAffinity: None
  type: ClusterIP
